component_depth: 1
languages:
- java

exclude:
- /src/dkeep/gui/.*
- .*/LevelEditor\.java
- .*/Settings\.java
- .*/DrawImage\.java
- .*/MainMenu\.java
- .*/MyButton\.java
- .*/NewGame\.java
- .*/Playground\.java
- .*/MapEditor\.java
- /src/dkeep/cli/.*
- .*/UserInteraction\.java
